# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scale.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(850, 752)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mass = QtGui.QLCDNumber(self.centralwidget)
        self.mass.setGeometry(QtCore.QRect(120, 50, 201, 41))
        self.mass.setNumDigits(7)
        self.mass.setDigitCount(7)
        self.mass.setProperty("value", 162.63)
        self.mass.setObjectName(_fromUtf8("mass"))
        self.static_teza = QtGui.QLabel(self.centralwidget)
        self.static_teza.setGeometry(QtCore.QRect(20, 60, 68, 17))
        self.static_teza.setObjectName(_fromUtf8("static_teza"))
        self.unit = QtGui.QLabel(self.centralwidget)
        self.unit.setGeometry(QtCore.QRect(330, 70, 68, 17))
        self.unit.setObjectName(_fromUtf8("unit"))
        self.save = QtGui.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(670, 520, 99, 27))
        self.save.setObjectName(_fromUtf8("save"))
        self.serial_port = QtGui.QComboBox(self.centralwidget)
        self.serial_port.setGeometry(QtCore.QRect(530, 210, 131, 27))
        self.serial_port.setObjectName(_fromUtf8("serial_port"))
        self.serial_port.addItem(_fromUtf8(""))
        self.serial_boud = QtGui.QComboBox(self.centralwidget)
        self.serial_boud.setGeometry(QtCore.QRect(530, 250, 131, 27))
        self.serial_boud.setObjectName(_fromUtf8("serial_boud"))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_connect = QtGui.QPushButton(self.centralwidget)
        self.serial_connect.setGeometry(QtCore.QRect(530, 290, 131, 27))
        self.serial_connect.setObjectName(_fromUtf8("serial_connect"))
        self.tara = QtGui.QLineEdit(self.centralwidget)
        self.tara.setGeometry(QtCore.QRect(20, 220, 121, 41))
        self.tara.setObjectName(_fromUtf8("tara"))
        self.set_to_zero = QtGui.QPushButton(self.centralwidget)
        self.set_to_zero.setGeometry(QtCore.QRect(170, 230, 99, 27))
        self.set_to_zero.setObjectName(_fromUtf8("set_to_zero"))
        self.static_status = QtGui.QLabel(self.centralwidget)
        self.static_status.setGeometry(QtCore.QRect(20, 20, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.static_status.setFont(font)
        self.static_status.setObjectName(_fromUtf8("static_status"))
        self.status = QtGui.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(140, 20, 31, 17))
        self.status.setObjectName(_fromUtf8("status"))
        self.static_tara = QtGui.QLabel(self.centralwidget)
        self.static_tara.setGeometry(QtCore.QRect(20, 190, 68, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.static_tara.setFont(font)
        self.static_tara.setObjectName(_fromUtf8("static_tara"))
        self.static_serial = QtGui.QLabel(self.centralwidget)
        self.static_serial.setGeometry(QtCore.QRect(530, 180, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.static_serial.setFont(font)
        self.static_serial.setObjectName(_fromUtf8("static_serial"))
        self.static_save = QtGui.QLabel(self.centralwidget)
        self.static_save.setGeometry(QtCore.QRect(500, 530, 131, 17))
        self.static_save.setObjectName(_fromUtf8("static_save"))
        self.static_env = QtGui.QLabel(self.centralwidget)
        self.static_env.setGeometry(QtCore.QRect(530, 20, 201, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.static_env.setFont(font)
        self.static_env.setObjectName(_fromUtf8("static_env"))
        self.static_tlak = QtGui.QLabel(self.centralwidget)
        self.static_tlak.setGeometry(QtCore.QRect(530, 60, 68, 17))
        self.static_tlak.setObjectName(_fromUtf8("static_tlak"))
        self.tlak = QtGui.QLabel(self.centralwidget)
        self.tlak.setGeometry(QtCore.QRect(590, 60, 68, 17))
        self.tlak.setObjectName(_fromUtf8("tlak"))
        self.static_temp = QtGui.QLabel(self.centralwidget)
        self.static_temp.setGeometry(QtCore.QRect(680, 60, 68, 17))
        self.static_temp.setObjectName(_fromUtf8("static_temp"))
        self.temp = QtGui.QLabel(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(740, 60, 68, 17))
        self.temp.setObjectName(_fromUtf8("temp"))
        self.static_humidity = QtGui.QLabel(self.centralwidget)
        self.static_humidity.setGeometry(QtCore.QRect(530, 90, 68, 17))
        self.static_humidity.setObjectName(_fromUtf8("static_humidity"))
        self.humidity = QtGui.QLabel(self.centralwidget)
        self.humidity.setGeometry(QtCore.QRect(590, 90, 68, 17))
        self.humidity.setObjectName(_fromUtf8("humidity"))
        self.static_multiple = QtGui.QLabel(self.centralwidget)
        self.static_multiple.setGeometry(QtCore.QRect(20, 310, 171, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.static_multiple.setFont(font)
        self.static_multiple.setObjectName(_fromUtf8("static_multiple"))
        self.static_stevilo = QtGui.QLabel(self.centralwidget)
        self.static_stevilo.setGeometry(QtCore.QRect(20, 340, 68, 17))
        self.static_stevilo.setObjectName(_fromUtf8("static_stevilo"))
        self.count = QtGui.QLabel(self.centralwidget)
        self.count.setGeometry(QtCore.QRect(80, 340, 68, 17))
        self.count.setObjectName(_fromUtf8("count"))
        self.weight = QtGui.QLineEdit(self.centralwidget)
        self.weight.setGeometry(QtCore.QRect(110, 370, 121, 41))
        self.weight.setObjectName(_fromUtf8("weight"))
        self.static_teza_enega = QtGui.QLabel(self.centralwidget)
        self.static_teza_enega.setGeometry(QtCore.QRect(20, 380, 81, 17))
        self.static_teza_enega.setObjectName(_fromUtf8("static_teza_enega"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 380, 99, 27))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.refresh_env_data = QtGui.QPushButton(self.centralwidget)
        self.refresh_env_data.setGeometry(QtCore.QRect(720, 90, 99, 27))
        self.refresh_env_data.setObjectName(_fromUtf8("refresh_env_data"))
        self.static_teza_2 = QtGui.QLabel(self.centralwidget)
        self.static_teza_2.setGeometry(QtCore.QRect(20, 110, 91, 17))
        self.static_teza_2.setObjectName(_fromUtf8("static_teza_2"))
        self.status_2 = QtGui.QLabel(self.centralwidget)
        self.status_2.setGeometry(QtCore.QRect(140, 110, 68, 17))
        self.status_2.setObjectName(_fromUtf8("status_2"))
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 530, 99, 27))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.static_multiple_2 = QtGui.QLabel(self.centralwidget)
        self.static_multiple_2.setGeometry(QtCore.QRect(20, 490, 231, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.static_multiple_2.setFont(font)
        self.static_multiple_2.setObjectName(_fromUtf8("static_multiple_2"))
        self.static_stevilo_2 = QtGui.QLabel(self.centralwidget)
        self.static_stevilo_2.setGeometry(QtCore.QRect(20, 530, 68, 17))
        self.static_stevilo_2.setObjectName(_fromUtf8("static_stevilo_2"))
        self.count_2 = QtGui.QLabel(self.centralwidget)
        self.count_2.setGeometry(QtCore.QRect(80, 530, 68, 17))
        self.count_2.setObjectName(_fromUtf8("count_2"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 620, 791, 71))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.static_multiple_3 = QtGui.QLabel(self.centralwidget)
        self.static_multiple_3.setGeometry(QtCore.QRect(20, 600, 231, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.static_multiple_3.setFont(font)
        self.static_multiple_3.setObjectName(_fromUtf8("static_multiple_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.refresh_env_data, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.updateEnvData)
        QtCore.QObject.connect(self.save, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.saveToFile)
        QtCore.QObject.connect(self.set_to_zero, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.setToZero)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.countPieces)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.calculatePieces)
        QtCore.QObject.connect(self.serial_connect, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.connectSerial)
        QtCore.QObject.connect(self.serial_port, QtCore.SIGNAL(_fromUtf8("activated(int)")), MainWindow.findSerial)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Tehtnica", None))
        self.static_teza.setText(_translate("MainWindow", "Teza:", None))
        self.unit.setText(_translate("MainWindow", "g", None))
        self.save.setText(_translate("MainWindow", "Shrani kot...", None))
        self.serial_port.setItemText(0, _translate("MainWindow", "choose serial", None))
        self.serial_boud.setItemText(0, _translate("MainWindow", "2400", None))
        self.serial_boud.setItemText(1, _translate("MainWindow", "4800", None))
        self.serial_boud.setItemText(2, _translate("MainWindow", "9600", None))
        self.serial_boud.setItemText(3, _translate("MainWindow", "19200", None))
        self.serial_boud.setItemText(4, _translate("MainWindow", "57200", None))
        self.serial_boud.setItemText(5, _translate("MainWindow", "115200", None))
        self.serial_boud.setItemText(6, _translate("MainWindow", "...", None))
        self.serial_connect.setText(_translate("MainWindow", "connect", None))
        self.tara.setToolTip(_translate("MainWindow", "<html><head/><body><p>trenutna tara</p></body></html>", None))
        self.tara.setText(_translate("MainWindow", "30", None))
        self.set_to_zero.setText(_translate("MainWindow", "Set zero", None))
        self.static_status.setText(_translate("MainWindow", "Status tehtnice:", None))
        self.status.setText(_translate("MainWindow", "S", None))
        self.static_tara.setText(_translate("MainWindow", "Tara", None))
        self.static_serial.setText(_translate("MainWindow", "Serial port", None))
        self.static_save.setText(_translate("MainWindow", "Shrani v datoteko:", None))
        self.static_env.setText(_translate("MainWindow", "Okoljski podatki", None))
        self.static_tlak.setText(_translate("MainWindow", "Tlak:", None))
        self.tlak.setText(_translate("MainWindow", "TextLabel", None))
        self.static_temp.setText(_translate("MainWindow", "Temp:", None))
        self.temp.setText(_translate("MainWindow", "TextLabel", None))
        self.static_humidity.setText(_translate("MainWindow", "Vlaga:", None))
        self.humidity.setText(_translate("MainWindow", "TextLabel", None))
        self.static_multiple.setText(_translate("MainWindow", "Štetje predmetov", None))
        self.static_stevilo.setText(_translate("MainWindow", "Število:", None))
        self.count.setText(_translate("MainWindow", "5", None))
        self.static_teza_enega.setText(_translate("MainWindow", "Teža enega:", None))
        self.pushButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Pritisni za tehtanje enega predmeta, ali pa vnesi težo</p></body></html>", None))
        self.pushButton_6.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.pushButton_6.setText(_translate("MainWindow", "1 komad", None))
        self.refresh_env_data.setText(_translate("MainWindow", "refresh", None))
        self.static_teza_2.setText(_translate("MainWindow", "Odzivni čas:", None))
        self.status_2.setText(_translate("MainWindow", "5", None))
        self.pushButton_7.setText(_translate("MainWindow", "start/stop", None))
        self.static_multiple_2.setText(_translate("MainWindow", "Tehtanje večih predmetov", None))
        self.static_stevilo_2.setText(_translate("MainWindow", "število:", None))
        self.count_2.setText(_translate("MainWindow", "3", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.static_multiple_3.setText(_translate("MainWindow", "Event log", None))


class MainWindow(QtGui.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)

