# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scale.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1102, 916)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mass = QtGui.QLCDNumber(self.centralwidget)
        self.mass.setGeometry(QtCore.QRect(120, 60, 201, 41))
        self.mass.setNumDigits(7)
        self.mass.setDigitCount(7)
        self.mass.setObjectName(_fromUtf8("mass"))
        self.static_teza = QtGui.QLabel(self.centralwidget)
        self.static_teza.setGeometry(QtCore.QRect(20, 70, 68, 17))
        self.static_teza.setObjectName(_fromUtf8("static_teza"))
        self.unit = QtGui.QLabel(self.centralwidget)
        self.unit.setGeometry(QtCore.QRect(330, 80, 68, 17))
        self.unit.setObjectName(_fromUtf8("unit"))
        self.save = QtGui.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(220, 750, 99, 27))
        self.save.setObjectName(_fromUtf8("save"))
        self.serial_port = QtGui.QComboBox(self.centralwidget)
        self.serial_port.setGeometry(QtCore.QRect(850, 90, 131, 27))
        self.serial_port.setObjectName(_fromUtf8("serial_port"))
        self.serial_port.addItem(_fromUtf8(""))
        self.serial_boud = QtGui.QComboBox(self.centralwidget)
        self.serial_boud.setGeometry(QtCore.QRect(850, 130, 131, 27))
        self.serial_boud.setObjectName(_fromUtf8("serial_boud"))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_boud.addItem(_fromUtf8(""))
        self.serial_connect = QtGui.QPushButton(self.centralwidget)
        self.serial_connect.setGeometry(QtCore.QRect(850, 170, 131, 27))
        self.serial_connect.setObjectName(_fromUtf8("serial_connect"))
        self.tara = QtGui.QLineEdit(self.centralwidget)
        self.tara.setGeometry(QtCore.QRect(10, 220, 121, 41))
        self.tara.setObjectName(_fromUtf8("tara"))
        self.set_to_zero = QtGui.QPushButton(self.centralwidget)
        self.set_to_zero.setGeometry(QtCore.QRect(160, 230, 99, 27))
        self.set_to_zero.setObjectName(_fromUtf8("set_to_zero"))
        self.static_status = QtGui.QLabel(self.centralwidget)
        self.static_status.setGeometry(QtCore.QRect(20, 20, 68, 17))
        self.static_status.setObjectName(_fromUtf8("static_status"))
        self.status = QtGui.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(110, 20, 68, 17))
        self.status.setObjectName(_fromUtf8("status"))
        self.static_tara = QtGui.QLabel(self.centralwidget)
        self.static_tara.setGeometry(QtCore.QRect(160, 200, 68, 17))
        self.static_tara.setObjectName(_fromUtf8("static_tara"))
        self.static_serial = QtGui.QLabel(self.centralwidget)
        self.static_serial.setGeometry(QtCore.QRect(840, 50, 68, 17))
        self.static_serial.setObjectName(_fromUtf8("static_serial"))
        self.static_save = QtGui.QLabel(self.centralwidget)
        self.static_save.setGeometry(QtCore.QRect(50, 760, 131, 17))
        self.static_save.setObjectName(_fromUtf8("static_save"))
        self.command = QtGui.QLineEdit(self.centralwidget)
        self.command.setGeometry(QtCore.QRect(850, 320, 121, 41))
        self.command.setObjectName(_fromUtf8("command"))
        self.send_command = QtGui.QPushButton(self.centralwidget)
        self.send_command.setGeometry(QtCore.QRect(870, 380, 99, 27))
        self.send_command.setObjectName(_fromUtf8("send_command"))
        self.static_ukaz = QtGui.QLabel(self.centralwidget)
        self.static_ukaz.setGeometry(QtCore.QRect(880, 290, 68, 17))
        self.static_ukaz.setObjectName(_fromUtf8("static_ukaz"))
        self.static_env = QtGui.QLabel(self.centralwidget)
        self.static_env.setGeometry(QtCore.QRect(490, 10, 201, 17))
        self.static_env.setObjectName(_fromUtf8("static_env"))
        self.static_tlak = QtGui.QLabel(self.centralwidget)
        self.static_tlak.setGeometry(QtCore.QRect(450, 50, 68, 17))
        self.static_tlak.setObjectName(_fromUtf8("static_tlak"))
        self.tlak = QtGui.QLabel(self.centralwidget)
        self.tlak.setGeometry(QtCore.QRect(510, 50, 68, 17))
        self.tlak.setObjectName(_fromUtf8("tlak"))
        self.static_temp = QtGui.QLabel(self.centralwidget)
        self.static_temp.setGeometry(QtCore.QRect(590, 50, 68, 17))
        self.static_temp.setObjectName(_fromUtf8("static_temp"))
        self.temp = QtGui.QLabel(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(670, 50, 68, 17))
        self.temp.setObjectName(_fromUtf8("temp"))
        self.static_humidity = QtGui.QLabel(self.centralwidget)
        self.static_humidity.setGeometry(QtCore.QRect(450, 80, 68, 17))
        self.static_humidity.setObjectName(_fromUtf8("static_humidity"))
        self.humidity = QtGui.QLabel(self.centralwidget)
        self.humidity.setGeometry(QtCore.QRect(500, 80, 68, 17))
        self.humidity.setObjectName(_fromUtf8("humidity"))
        self.static_multiple = QtGui.QLabel(self.centralwidget)
        self.static_multiple.setGeometry(QtCore.QRect(130, 470, 68, 17))
        self.static_multiple.setObjectName(_fromUtf8("static_multiple"))
        self.static_stevilo = QtGui.QLabel(self.centralwidget)
        self.static_stevilo.setGeometry(QtCore.QRect(40, 510, 68, 17))
        self.static_stevilo.setObjectName(_fromUtf8("static_stevilo"))
        self.count = QtGui.QLabel(self.centralwidget)
        self.count.setGeometry(QtCore.QRect(100, 510, 68, 17))
        self.count.setObjectName(_fromUtf8("count"))
        self.weight = QtGui.QLineEdit(self.centralwidget)
        self.weight.setGeometry(QtCore.QRect(280, 500, 121, 41))
        self.weight.setObjectName(_fromUtf8("weight"))
        self.static_teza_enega = QtGui.QLabel(self.centralwidget)
        self.static_teza_enega.setGeometry(QtCore.QRect(190, 510, 81, 17))
        self.static_teza_enega.setObjectName(_fromUtf8("static_teza_enega"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(420, 510, 99, 27))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.refresh_env_data = QtGui.QPushButton(self.centralwidget)
        self.refresh_env_data.setGeometry(QtCore.QRect(640, 80, 99, 27))
        self.refresh_env_data.setObjectName(_fromUtf8("refresh_env_data"))
        self.return_data = QtGui.QLineEdit(self.centralwidget)
        self.return_data.setGeometry(QtCore.QRect(740, 440, 221, 41))
        self.return_data.setObjectName(_fromUtf8("return_data"))
        self.static_teza_2 = QtGui.QLabel(self.centralwidget)
        self.static_teza_2.setGeometry(QtCore.QRect(10, 130, 91, 17))
        self.static_teza_2.setObjectName(_fromUtf8("static_teza_2"))
        self.status_2 = QtGui.QLabel(self.centralwidget)
        self.status_2.setGeometry(QtCore.QRect(120, 130, 68, 17))
        self.status_2.setObjectName(_fromUtf8("status_2"))
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 650, 99, 27))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.static_multiple_2 = QtGui.QLabel(self.centralwidget)
        self.static_multiple_2.setGeometry(QtCore.QRect(110, 610, 68, 17))
        self.static_multiple_2.setObjectName(_fromUtf8("static_multiple_2"))
        self.static_stevilo_2 = QtGui.QLabel(self.centralwidget)
        self.static_stevilo_2.setGeometry(QtCore.QRect(20, 650, 68, 17))
        self.static_stevilo_2.setObjectName(_fromUtf8("static_stevilo_2"))
        self.count_2 = QtGui.QLabel(self.centralwidget)
        self.count_2.setGeometry(QtCore.QRect(80, 650, 68, 17))
        self.count_2.setObjectName(_fromUtf8("count_2"))
        self.serial_port_2 = QtGui.QComboBox(self.centralwidget)
        self.serial_port_2.setGeometry(QtCore.QRect(740, 330, 85, 27))
        self.serial_port_2.setObjectName(_fromUtf8("serial_port_2"))
        self.serial_port_2.addItem(_fromUtf8(""))
        self.serial_port_2.addItem(_fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.refresh_env_data, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.updateEnvData)
        QtCore.QObject.connect(self.save, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.saveToFile)
        QtCore.QObject.connect(self.set_to_zero, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.setToZero)
        QtCore.QObject.connect(self.send_command, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sendCommand)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.countPieces)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.calculatePieces)
        QtCore.QObject.connect(self.serial_connect, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.connectSerial)
        QtCore.QObject.connect(self.serial_port, QtCore.SIGNAL(_fromUtf8("activated(int)")), MainWindow.findSerial)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.static_teza.setText(_translate("MainWindow", "Teza", None))
        self.unit.setText(_translate("MainWindow", "g", None))
        self.save.setText(_translate("MainWindow", "Shrani kot...", None))
        self.serial_port.setItemText(0, _translate("MainWindow", "choose serial", None))
        self.serial_boud.setItemText(0, _translate("MainWindow", "2400", None))
        self.serial_boud.setItemText(1, _translate("MainWindow", "4800", None))
        self.serial_boud.setItemText(2, _translate("MainWindow", "9600", None))
        self.serial_boud.setItemText(3, _translate("MainWindow", "19200", None))
        self.serial_boud.setItemText(4, _translate("MainWindow", "57200", None))
        self.serial_boud.setItemText(5, _translate("MainWindow", "115200", None))
        self.serial_boud.setItemText(6, _translate("MainWindow", "...", None))
        self.serial_connect.setText(_translate("MainWindow", "connect", None))
        self.set_to_zero.setText(_translate("MainWindow", "Set zero", None))
        self.static_status.setText(_translate("MainWindow", "Status", None))
        self.status.setText(_translate("MainWindow", "TextLabel", None))
        self.static_tara.setText(_translate("MainWindow", "Tara", None))
        self.static_serial.setText(_translate("MainWindow", "Serial", None))
        self.static_save.setText(_translate("MainWindow", "Shrani v datoteko:", None))
        self.send_command.setText(_translate("MainWindow", "Send", None))
        self.static_ukaz.setText(_translate("MainWindow", "Pošli ukaz", None))
        self.static_env.setText(_translate("MainWindow", "Okoljski podatki", None))
        self.static_tlak.setText(_translate("MainWindow", "Tlak", None))
        self.tlak.setText(_translate("MainWindow", "TextLabel", None))
        self.static_temp.setText(_translate("MainWindow", "temp", None))
        self.temp.setText(_translate("MainWindow", "TextLabel", None))
        self.static_humidity.setText(_translate("MainWindow", "vlaga", None))
        self.humidity.setText(_translate("MainWindow", "TextLabel", None))
        self.static_multiple.setText(_translate("MainWindow", "multiple", None))
        self.static_stevilo.setText(_translate("MainWindow", "stevilo", None))
        self.count.setText(_translate("MainWindow", "TextLabel", None))
        self.static_teza_enega.setText(_translate("MainWindow", "teza enega", None))
        self.pushButton_6.setText(_translate("MainWindow", "1 komad", None))
        self.refresh_env_data.setText(_translate("MainWindow", "refresh", None))
        self.static_teza_2.setText(_translate("MainWindow", "Odzivni čas", None))
        self.status_2.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton_7.setText(_translate("MainWindow", "start/stop", None))
        self.static_multiple_2.setText(_translate("MainWindow", "stetje", None))
        self.static_stevilo_2.setText(_translate("MainWindow", "stevilo", None))
        self.count_2.setText(_translate("MainWindow", "TextLabel", None))
        self.serial_port_2.setItemText(0, _translate("MainWindow", "SI", None))
        self.serial_port_2.setItemText(1, _translate("MainWindow", "SIR", None))


class MainWindow(QtGui.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)

